# Generated by Django 3.0.5 on 2020-04-26 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='trip_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50, verbose_name='Place of origin')),
                ('destination', models.CharField(max_length=50, verbose_name='Trip Destination')),
                ('Date', models.DateField(verbose_name='Trip Date')),
                ('Time', models.TimeField(verbose_name='Trip Time')),
                ('PostDate', models.DateField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Please provide a description of your Trip')),
                ('agency', models.CharField(max_length=50, verbose_name='Travelling agency used')),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='', verbose_name='Image about Trip')),
                ('is_public', models.BooleanField(default=True, verbose_name='Pushish Trip')),
                ('author', models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='join_trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_data_id', models.IntegerField()),
                ('joinin_user', models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
