# Generated by Django 3.0.5 on 2020-04-28 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_data_id', models.IntegerField()),
                ('comment_date_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('thumb', models.ImageField(blank=True, default=None, upload_to='')),
                ('commenting_user', models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
