# Generated by Django 3.0.5 on 2020-05-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_manager', '0003_auto_20200523_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_data',
            name='group_exist',
            field=models.BooleanField(default=False),
        ),
    ]
